package org.example;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Insets;
import java.io.File;
import java.util.Arrays;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;

public class Dashboard extends JFrame {

  private static final String CHOOSE_FILE = "Choose File";
  private static final String CHOOSE_FILE_LOCATION = "Choose File Location";
  private static final String COMPARE_RISE_BILLER_AND_PROVIDER = "Compare Rise Biller and Provider";
  private static final String NO_FILE_SELECTED = "No file selected.";
  private static final String PROVIDER_LIST = "provider.list";
  private JPanel MainPanel;
  private JButton chooseLocationButton;
  private JButton providerButton;
  private JComboBox<String> providerCombo;
  private File providerFile;
  private JButton riseButton;
  private File riseFile;
  private JButton submitButton;

  public Dashboard() {
    makeComboBoxLabelCenter();
    generateProviderConfig();
    setContentPane(MainPanel);
    setTitle(COMPARE_RISE_BILLER_AND_PROVIDER);
    setDefaultCloseOperation(EXIT_ON_CLOSE);
    setSize(600, 300);
    setLocationRelativeTo(null);
    riseButton.addActionListener(e -> openFileChooser(true));
    providerButton.setEnabled(false);
    chooseLocationButton.setEnabled(false);
    submitButton.setEnabled(false);
    providerButton.addActionListener(e -> openFileChooser(false));
    chooseLocationButton.addActionListener(e -> chooseOutputDirectory());
    setVisible(true);
    submitButton.addActionListener(e -> reconciliation(riseFile, providerFile));
  }

  public static void main(String[] args) {
    new Dashboard();
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR call it in your
   * code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    MainPanel = new JPanel();
    MainPanel.setLayout(new GridLayoutManager(5, 9, new Insets(0, 0, 0, 0), -1, -1));
    MainPanel.setBackground(new Color(-516));
    final JLabel label1 = new JLabel();
    label1.setHorizontalTextPosition(0);
    label1.setText("File Provider");
    MainPanel.add(label1, new GridConstraints(2, 1, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
      GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final JLabel label2 = new JLabel();
    label2.setText("Provider");
    MainPanel.add(label2, new GridConstraints(0, 1, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
      GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final JLabel label3 = new JLabel();
    label3.setText("Result File Location");
    MainPanel.add(label3, new GridConstraints(3, 1, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
      GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    providerButton = new JButton();
    providerButton.setText("Choose File");
    MainPanel.add(providerButton,
      new GridConstraints(2, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED,
        null, null, null, 0, false));
    providerCombo = new JComboBox();
    Font providerComboFont = this.$$$getFont$$$(null, -1, 12, providerCombo.getFont());
    if (providerComboFont != null) {
      providerCombo.setFont(providerComboFont);
    }
    final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
    providerCombo.setModel(defaultComboBoxModel1);
    MainPanel.add(providerCombo,
      new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL,
        GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    riseButton = new JButton();
    riseButton.setHideActionText(false);
    riseButton.setText("Chose File");
    MainPanel.add(riseButton,
      new GridConstraints(1, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED,
        null, null, null, 0, false));
    chooseLocationButton = new JButton();
    chooseLocationButton.setText("Choose File Location");
    MainPanel.add(chooseLocationButton,
      new GridConstraints(3, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED,
        null, null, null, 0, false));
    submitButton = new JButton();
    submitButton.setHorizontalTextPosition(0);
    submitButton.setText("Submit");
    MainPanel.add(submitButton,
      new GridConstraints(4, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED,
        null, null, null, 0, false));
    final JLabel label4 = new JLabel();
    label4.setBackground(new Color(-16777216));
    label4.setText("File Rise");
    MainPanel.add(label4, new GridConstraints(1, 1, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
      GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final JLabel label5 = new JLabel();
    label5.setText("");
    MainPanel.add(label5, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
      GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final JLabel label6 = new JLabel();
    label6.setText("");
    MainPanel.add(label6, new GridConstraints(0, 5, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
      GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
  }

  /**
   * @noinspection ALL
   */
  private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
    if (currentFont == null) {
      return null;
    }
    String resultName;
    if (fontName == null) {
      resultName = currentFont.getName();
    } else {
      Font testFont = new Font(fontName, Font.PLAIN, 10);
      if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
        resultName = fontName;
      } else {
        resultName = currentFont.getName();
      }
    }
    Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(),
      size >= 0 ? size : currentFont.getSize());
    boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
    Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize())
      : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
    return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return MainPanel;
  }

  private void chooseOutputDirectory() {
    final JFileChooser chooser = new JFileChooser();
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    final int result = chooser.showSaveDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
      chooseLocationButton.setText(chooser.getSelectedFile().getAbsolutePath());
      submitButton.setEnabled(true);
    }
  }

  private void generateProviderConfig() {
    final String providerList = AppConfig.getProperties(PROVIDER_LIST);
    providerCombo.addItem("---- choose provider ----");
    Arrays.stream(providerList.split(",")).forEach(provider -> {
      providerCombo.addItem(provider);
    });
  }

  private void makeComboBoxLabelCenter() {
    providerCombo.setRenderer(new DefaultListCellRenderer() {
      @Override
      public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected,
        boolean cellHasFocus) {
        JLabel label = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
        label.setHorizontalAlignment(SwingConstants.CENTER);
        return label;
      }
    });
  }

  private void openFileChooser(boolean isRise) {
    final JFileChooser chooser = new JFileChooser();
    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
      final File selected = chooser.getSelectedFile();
      if (selected == null) {
        JOptionPane.showMessageDialog(this, NO_FILE_SELECTED);
        return;
      }
      if (isRise) {
        riseFile = selected;
        riseButton.setText(selected.getName());
        providerButton.setEnabled(true);
      } else {
        providerFile = selected;
        providerButton.setText(selected.getName());
        chooseLocationButton.setEnabled(true);
      }
    }
  }

  private void reconciliation(File riseFile, File providerFile) {
    final TransactionService transactionService = new TransactionService();
    final String reconStatusMessage = transactionService.generateResultFile(providerFile, riseFile,
      (String) providerCombo.getSelectedItem(), chooseLocationButton.getText());
    JOptionPane.showMessageDialog(this, reconStatusMessage);
    resetFields();
  }

  private void resetFields() {
    providerButton.setEnabled(false);
    submitButton.setEnabled(false);
    chooseLocationButton.setEnabled(false);
    providerButton.setText(CHOOSE_FILE);
    riseButton.setText(CHOOSE_FILE);
    chooseLocationButton.setText(CHOOSE_FILE_LOCATION);
    riseFile = null;
    providerFile = null;
  }

}
